2023-06-20 09:15:18,164 INFO    MainThread:10148 [wandb_setup.py:_flush():76] Current SDK version is 0.15.3
2023-06-20 09:15:18,166 INFO    MainThread:10148 [wandb_setup.py:_flush():76] Configure stats pid to 10148
2023-06-20 09:15:18,166 INFO    MainThread:10148 [wandb_setup.py:_flush():76] Loading settings from C:\Users\Roumaissa\.config\wandb\settings
2023-06-20 09:15:18,167 INFO    MainThread:10148 [wandb_setup.py:_flush():76] Loading settings from C:\Users\Roumaissa\Desktop\Thesis\againtry\wandb\settings
2023-06-20 09:15:18,168 INFO    MainThread:10148 [wandb_setup.py:_flush():76] Loading settings from environment variables: {}
2023-06-20 09:15:18,169 INFO    MainThread:10148 [wandb_setup.py:_flush():76] Applying setup settings: {'_disable_service': False}
2023-06-20 09:15:18,170 INFO    MainThread:10148 [wandb_setup.py:_flush():76] Inferring run settings from compute environment: {'program_relpath': 'test_ray_3_R.py', 'program': 'C:/Users/Roumaissa/Desktop/Thesis/againtry/test_ray_3_R.py'}
2023-06-20 09:15:18,173 INFO    MainThread:10148 [wandb_init.py:_log_setup():507] Logging user logs to C:\Users\Roumaissa\Desktop\Thesis\againtry\wandb\run-20230620_091518-l23uxaa3\logs\debug.log
2023-06-20 09:15:18,176 INFO    MainThread:10148 [wandb_init.py:_log_setup():508] Logging internal logs to C:\Users\Roumaissa\Desktop\Thesis\againtry\wandb\run-20230620_091518-l23uxaa3\logs\debug-internal.log
2023-06-20 09:15:18,187 INFO    MainThread:10148 [wandb_init.py:init():547] calling init triggers
2023-06-20 09:15:18,188 INFO    MainThread:10148 [wandb_init.py:init():554] wandb.init called with sweep_config: {}
config: {}
2023-06-20 09:15:18,201 INFO    MainThread:10148 [wandb_init.py:init():596] starting backend
2023-06-20 09:15:18,202 INFO    MainThread:10148 [wandb_init.py:init():600] setting up manager
2023-06-20 09:15:18,296 INFO    MainThread:10148 [backend.py:_multiprocessing_setup():106] multiprocessing start_methods=spawn, using: spawn
2023-06-20 09:15:18,442 INFO    MainThread:10148 [wandb_init.py:init():606] backend started and connected
2023-06-20 09:15:18,522 INFO    MainThread:10148 [wandb_init.py:init():700] updated telemetry
2023-06-20 09:15:18,527 INFO    MainThread:10148 [wandb_init.py:init():737] communicating run to backend with 60.0 second timeout
2023-06-20 09:15:19,716 INFO    MainThread:10148 [wandb_run.py:_on_init():2177] communicating current version
2023-06-20 09:15:19,982 INFO    MainThread:10148 [wandb_run.py:_on_init():2186] got version response upgrade_message: "wandb version 0.15.4 is available!  To upgrade, please run:\n $ pip install wandb --upgrade"

2023-06-20 09:15:19,983 INFO    MainThread:10148 [wandb_init.py:init():787] starting run threads in backend
2023-06-20 09:15:20,577 INFO    MainThread:10148 [wandb_run.py:_console_start():2158] atexit reg
2023-06-20 09:15:20,584 INFO    MainThread:10148 [wandb_run.py:_redirect():2013] redirect: SettingsConsole.WRAP_RAW
2023-06-20 09:15:20,587 INFO    MainThread:10148 [wandb_run.py:_redirect():2078] Wrapping output streams.
2023-06-20 09:15:20,588 INFO    MainThread:10148 [wandb_run.py:_redirect():2103] Redirects installed.
2023-06-20 09:15:20,595 INFO    MainThread:10148 [wandb_init.py:init():829] run started, returning control to user process
2023-06-20 09:27:57,208 ERROR   MainThread:10148 [wandb_init.py:init():1178] error
Traceback (most recent call last):
  File "C:\Users\Roumaissa\Desktop\Thesis\againtry\venv\lib\site-packages\wandb\sdk\wandb_init.py", line 1146, in init
    wi.setup(kwargs)
  File "C:\Users\Roumaissa\Desktop\Thesis\againtry\venv\lib\site-packages\wandb\sdk\wandb_init.py", line 303, in setup
    settings._apply_init(kwargs)
  File "C:\Users\Roumaissa\Desktop\Thesis\againtry\venv\lib\site-packages\wandb\sdk\wandb_settings.py", line 1745, in _apply_init
    self.update(init_settings, source=Source.INIT)
  File "C:\Users\Roumaissa\Desktop\Thesis\againtry\venv\lib\site-packages\wandb\sdk\wandb_settings.py", line 1421, in update
    raise KeyError(f"Unknown settings: {unknown_properties}")
KeyError: "Unknown settings: ['__pydevd_ret_val_dict']"
2023-06-20 09:28:06,700 WARNING MsgRouterThr:10148 [router.py:message_loop():77] message_loop has been closed
